# Generated by Django 5.0.1 on 2024-01-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=120)),
                ('desc', models.CharField(max_length=470)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=120)),
                ('user_id', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('user_first_name', models.CharField(max_length=155)),
                ('user_last_name', models.CharField(max_length=155)),
            ],
        ),
    ]
