# Generated by Django 5.0.1 on 2024-01-24 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loppisappen', '0002_user_market_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market_ad',
            old_name='titel',
            new_name='title',
        ),
        migrations.AddField(
            model_name='market_ad',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 10, 3, 29, 526268)),
        ),
    ]
